# Quarkus datasource configuration
# In dev and test mode Dev Services starts a PostgreSQL container automatically
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=${TEAMPLANNER_DB_URL}
%prod.quarkus.datasource.username=${TEAMPLANNER_DB_USER}
%prod.quarkus.datasource.password=${TEAMPLANNER_DB_PASSWORD}
quarkus.hibernate-orm.schema-management.strategy=drop-and-create

# Quarkus Search configuration
# In dev and test mode Dev Services starts an Elasticsearch container automatically
quarkus.hibernate-search-orm.elasticsearch.version=9
%prod.quarkus.hibernate-search-orm.elasticsearch.hosts=${TEAMPLANNER_ELASTICSEARCH_HOSTS}
# quarkus.hibernate-search-orm.elasticsearch.analysis.configurer=nl.paston.teamplanner.search.AnalysisConfigurer
quarkus.hibernate-search-orm.indexing.plan.synchronization.strategy=sync
quarkus.hibernate-search-orm.schema-management.strategy=drop-and-create-and-drop
quarkus.hibernate-search-orm.elasticsearch.schema-management.required-status=yellow

# Quarkus HTTP configuration
quarkus.http.cors.enabled=true
quarkus.swagger-ui.always-include=true
quarkus.http.enable-compression=true
