insert into event (id, name, date, planned) values (1, 'Training', '2020-01-05', true);
insert into event (id, name, date, planned) values (2, 'Training', '2020-01-07', true);
insert into event (id, name, date, planned) values (3, 'Training', '2020-01-12', true);
insert into event (id, name, date, planned) values (4, 'Training', '2020-01-14', false);
insert into event (id, name, date, planned) values (5, 'Wedstrijd', '2020-01-19', false);
-- Events use fixed ids so member events can refer to them; move the sequence past them
alter sequence Event_SEQ restart with 100;
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Martijn Burger', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Sander Kroon', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Gertie Lintjes', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Niels van Maurik', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Harry Smorenburg', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Hein Hopmans', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Jeroen Loos', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Kevin de Wit', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Remco van der Panne', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Janet Corsius', 'AVAILABLE', 'ACCEPTED', 'Ik ben waarschijnlijk iets later.');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Wilbert Coumans', 'AVAILABLE', 'ACCEPTED', 'Sturen?');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 1, 'Vincent van Rijn', 'AVAILABLE', 'REJECTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Martijn Burger', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Sander Kroon', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Gertie Lintjes', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Niels van Maurik', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Harry Smorenburg', 'NOT_AVAILABLE', 'SKIPPED', 'Vakantie');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Hein Hopmans', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Jeroen Loos', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Kevin de Wit', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Remco van der Panne', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Janet Corsius', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Wilbert Coumans', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 2, 'Vincent van Rijn', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Sander Kroon', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Gertie Lintjes', 'AVAILABLE', 'REJECTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Niels van Maurik', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Harry Smorenburg', 'NOT_AVAILABLE', 'SKIPPED', 'Vakantie');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Hein Hopmans', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Jeroen Loos', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Kevin de Wit', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Remco van der Panne', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Janet Corsius', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Wilbert Coumans', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 3, 'Vincent van Rijn', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Martijn Burger', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Sander Kroon', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Gertie Lintjes', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Niels van Maurik', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Harry Smorenburg', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Hein Hopmans', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Jeroen Loos', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Kevin de Wit', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Remco van der Panne', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Janet Corsius', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Wilbert Coumans', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Vincent van Rijn', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Bas Schols', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 4, 'Erwin Mattherus', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Martijn Burger', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Sander Kroon', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Gertie Lintjes', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Niels van Maurik', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Harry Smorenburg', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Hein Hopmans', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Jeroen Loos', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Kevin de Wit', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Remco van der Panne', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Janet Corsius', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Wilbert Coumans', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Vincent van Rijn', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Bas Schols', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('MemberEvent_SEQ'), 5, 'Erwin Mattherus', 'WAITING', 'WAITING', '');
