insert into event (id, name, date) values (1, 'Training', '2020-01-05');
insert into event (id, name, date) values (2, 'Training', '2020-01-07');
insert into event (id, name, date) values (3, 'Training', '2020-01-12');
insert into event (id, name, date) values (4, 'Training', '2020-01-14');
insert into event (id, name, date) values (5, 'Wedstrijd', '2020-01-19');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 1, 'Martijn', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 1, 'Sander', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 1, 'Gertie', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 1, 'Janet', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 1, 'Vincent', 'AVAILABLE', 'REJECTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 2, 'Martijn', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 2, 'Sander', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 2, 'Gertie', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 2, 'Janet', 'AVAILABLE', 'ACCEPTED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 2, 'Vincent', 'NOT_AVAILABLE', 'SKIPPED', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 3, 'Martijn', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 3, 'Sander', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 3, 'Gertie', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 3, 'Janet', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 3, 'Vincent', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 4, 'Martijn', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 4, 'Sander', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 4, 'Gertie', 'NOT_AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 4, 'Janet', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 4, 'Vincent', 'WAITING', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 5, 'Martijn', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 5, 'Sander', 'AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 5, 'Gertie', 'NOT_AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 5, 'Janet', 'NOT_AVAILABLE', 'WAITING', '');
insert into memberevent (id, event_id, name, available, planned, comment) values (nextval('hibernate_sequence'), 5, 'Vincent', 'WAITING', 'WAITING', '');
