title: Teamplanner
description: >-
  Teamplanner is an open source project in progress. It is live 
  coded on twitch.tv and it's goal is to provide a webapplication
  that holds the planning for sportsteams.
remote_theme: chrisrhymes/bulma-clean-theme
url: https://www.teamplanner.net
github_username: martijnburger
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
show_excerpts: true
feed_icon: /assets/img/logo-small.png
sass:
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      hero_image: "/assets/img/hero.jpeg"  
      title: "Get on board"
      subtitle: "with Teamplanner!"   
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
