title: Teamplanner
tagline: Get on board
email: martijn@roeiploegutrecht.nl
description: >-
  Teamplanner is an open source project in progress. It is live 
  coded on twitch.tv and it's goal is to provide a webapplication
  that holds the planning for sportsteams.
remote_theme: chrisrhymes/bulma-clean-theme
url: https://www.teamplanner.net

paginate: 5
paginate_path: "/blog/page:num/"
disqus:
  shortname: martijn

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

show_excerpts: true
feed_icon: /assets/img/logo-small.png
sass:
  style: compressed
  source_dir: _sass
google_analytics: UA-153629949-1
markdown: kramdown
highlighter: rouge
footer_menu: footer

defaults:
  - scope:
      path: ""
    values:
      hero_image: "/assets/img/hero.jpeg"  
      title: "Get on board"
      subtitle: "with Teamplanner!"
      show_sidebar: true
  - scope:
      path: ""
      type: "posts"
    values:
      author: "Martijn Burger"  
