title: Teamplanner
description: >-
  Teamplanner is an open source project in progress. It is live 
  coded on twitch.tv and it's goal is to provide a webapplication
  that holds the planning for sportsteams.
show_downloads: false
theme: hitchens-theme
# theme: jekyll-theme-cayman
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
