source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "bulma-clean-theme", "~> 1.3"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-paginate"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end

# Needed for `jekyll serve` on Ruby 3
gem "webrick"
